### ISSUE TITLE
FTP Plugin doesn't show in UI if Optional Links are disabled

### ISSUE THREAD

**Issue by josh-abram** [cdgco/VestaWebInterface#129]
If optional links are disabled, but you want to enable the FTP plugin you must enable at least one optional link so that the hide menu appears allowing the link to the FTP plugin to be shown.

Ideally, if FTP plugin is enabled it should always show regardless of the Optional Links. 

Example of Optional Link Settings:

![image](https://user-images.githubusercontent.com/39235841/78002599-35dff080-7383-11ea-9ae0-2ba5ea4dbb57.png)

No link to FTP plugin appears in the Navigation pane:
![image](https://user-images.githubusercontent.com/39235841/78003139-f2d24d00-7383-11ea-9383-fb5ba67d01f2.png)

**Comment by cdgco** [comment]
Menu system wasn't checking to see if plugins were being placed in the 'Apps' section, so when all default apps were disabled, additional apps were also disabled. Fixed by adding `global $pluginsections;` to line 424 of `includes/includes.php`, and ` || in_array('apps', $pluginsections)` to the if statements in lines 442 & 450 of `includes/includes.php`,
