### ISSUE TITLE
Register sistem

### ISSUE THREAD

**Issue by endgame99** [cdgco/VestaWebInterface#130]
you can add email verification at registration?
Or register with Google or GloboFace?

**Comment by cdgco** [comment]
While it would definitely be possible to add email verification, I not sure there is an effective way to implement that while maintaining security. Since email verification would be linked only to VWI and not VestaCP itself, users could still access the classic VestaCP control panel without verification. I may be able to get around that by automatically suspending users until verified.

In order to add either email verification or 3rd party authentication, I would have to add another table to the VWI database in order to store verification status and link VestaCP accounts with VWI / 3rd party account IDs.

I will look into that, but I am not sure how long that may take to implement.

**Comment by spike99** [comment]
it is better and easier to make register with Google, Globoface, Facebook, etc, Email addresses are already validated

**Comment by cdgco** [comment]
@spikepower I'm not sure what you mean by email addresses are already verified. If registrations are enabled on VWI users can login to their account as soon as they make it, there is no verification email or MFA. 

@endgame99 I am currently adding social login / registration through Auth0. This system gives VWI 30+ 3rd party connections out of the box and gives the option for admins to add any custom integrations (such as Globoface) to VWI all through the same universal endpoint.

I have the API integration complete and am currently working on the login and registration systems. This will probably be done in 1 - 2 days and released in the next update. 

<hr>

![Social Login Preview](https://i.ibb.co/BLsYTJL/preview.png)

**Comment by cdgco** [comment]
The Auth0 integration is now complete and can be used immediately by doing a manual installation, or you can wait until the next release which will include this feature.

The documentation is available here: https://vwi.cdgtech.one/#/auth

**Comment by cdgco** [comment]
v2.2.0 is now available
#136
