### ISSUE TITLE
How to... translate?

### ISSUE THREAD

**Issue by ReNNoN** [cdgco/VestaWebInterface#24]
Hi !!!!

I tried to translate, changing the "msgstr" in the messages.po file of es_US, but the changes are not visible.
Any other way to translate without having to modify the "ECHO" of the .php files?

Thanks you!

**Comment by cdgco** [comment]
You don't need to edit any of the "echo" strings in the php files. Doing so will break the translation system. The problem is that translations are cached on the web server to save time. After you edit translations you must restart apache (`sudo service apache2 restart`) then the translations will show up.
