### ISSUE TITLE
Subdomains isn't working

### ISSUE THREAD

**Issue by ReNNoN** [cdgco/VestaWebInterface#25]
Hi,

when you add a new web domain in vwi or subdomain (like subdomain.maindomain.com) the external ip doesn't appear, only local ip and DNS domains/subdomains its configure automatically with a local ip, finally subdomain not working.

If you add subdomain in the vesta normal control panel, working perfectly.

Thanks u and seriouly, vwi is amazing, great work!

(I have installed the last version (v0.4.0-Beta))

**Comment by cdgco** [comment]
I'm not sure what exactly your problem is. It sounds like it may be a problem with your IP address setup for Vesta or a problem with nameservers but I could be wrong, if so it would be a problem with Vesta and not VWI. I don't know what you mean by subdomain don't work  but DNS subdomain do. Could you give more detail or explanation so I can attempt to diagnose or recreate the problem? Thanks!
