### ISSUE TITLE
CloudFlare integration

### ISSUE THREAD

**Issue by andresrobinson** [cdgco/VestaWebInterface#26]
Hi, It would be really nice to see an integration with Cloudflare for DNS management. It could be really useful and help reduce server load. cPanel already has a Plugin like that.

**Comment by cdgco** [comment]
I agree that this would be a great feature, but I'm not sure how capable I am at achieving this. I'll look into it, and while it is possible to create, it seems like this is more of a feature that VestaCP needs to add to their backend rather than myself.

I'd like to make this but this is not a core focus of the project and would likely take up too much time.

**Comment by cdgco** [comment]
I've been looking into the possibility, and it seems like it will take some time, but it will be easier to accomplish than I originally thought. Nevertheless, this feature will take a while to implement and will be challenging to develop if I do so. Along with this, it should be easy to apply the system I have in mind to a standalone plugin for VestaCP in the future.

**Comment by cdgco** [comment]
Basic support complete. To be released in v0.5.0-Beta.
