### ISSUE TITLE
Mobile phone support

### ISSUE THREAD

**Issue by tnttaolin2** [cdgco/VestaWebInterface#29]
Hi! I love the cpanel that you guys made for vesta but it would be cool if you guys add more support to mobile phone screen size. Thanks!

**Comment by cdgco** [comment]
Thank you for your interest! 

One of the main focuses of VWI is to create a great user experience on all devices, there are some problems and bugs still that will hopefully be fixed in the next release to create a better mobile experience, such as the login page for tablets or smaller screens, and the home page list functions, but there is currently quite a large amount of support for mobile devices. 

What in particular would make a better mobile experience in your opinion?

**Comment by tnttaolin2** [comment]
Manage domains page & information about the user. I think these are the most important.

**Comment by cdgco** [comment]
A new system has been put in place to responsively format data lists and will be rolled out for major pages soon. All pages will have this system by v0.5.0-Beta and stylistic bugs will be fixed following responsive updates.
