### ISSUE TITLE
FtpPlugin - HTTP ERROR 500

### ISSUE THREAD

**Issue by Plata-0-Plomo** [cdgco/VestaWebInterface#65]
Hello.

I have installed vesta fwi 0.5.3 beta and ftp plugin 0.1.2, but plug-in does not work. When i open the page, i getting HTTP ERROR 500 .

> Hi, could you please edit the '.htaccess' file in your installation and turn on debugging by changing the line php_flag display_errors off to php_flag display_errors on ?

I did it, the error remained the same, unchanged

Sorry, google translate ;)

**Comment by Plata-0-Plomo** [comment]
> Hi, could you please edit the '.htaccess' file in your installation and turn on debugging by changing the line php_flag display_errors off to php_flag display_errors on ?

I got next error (sorry, changes in htaccess was not saved):
Fatal error: Cannot redeclare vwicrypt() (previously declared in /home/hosting/web/panel.*******.**/public_html/includes/includes.php:298) in /home/hosting/web/panel.*******.**/public_html/includes/includes.php on line 298

**Comment by Plata-0-Plomo** [comment]
I noticed that when I turned on the error display, the list itself did not display the lists of domains, users. After turning off the error display, everything again worked.

**Comment by cdgco** [comment]
@Plata-0-Plomo The list going away is expected as the debugging setting causes errors in rendering because it places messages in the middle of the code. 

I believe I have found the cause of the error, which I have not experienced because you are using PHP 5.5 and I use PHP 7.0-7.2 for testing. Please delete your ftp plugin folder and upload the folder from the zip file I have linked below, then see if your error goes away.

[ftp-test.zip](https://github.com/cdgco/VestaWebInterface/files/2364135/ftp.zip)

**Comment by Plata-0-Plomo** [comment]
Unfortunately there are no visible changes.

Fatal error: Cannot redeclare vwicrypt() (previously declared in /home/hosting/web/panel.plomo.gq/public_html/includes/includes.php:298) in /home/hosting/web/panel.plomo.gq/public_html/includes/includes.php on line 298

**Comment by cdgco** [comment]
@Plata-0-Plomo Could you visit http://panel.plomo.gq/plugins/ftp/config.php with debugging enabled and see if you get the same error?

**Comment by Plata-0-Plomo** [comment]
Fatal error: Cannot redeclare vwicrypt() (previously declared in /home/hosting/web/panel.plomo.gq/public_html/includes/includes.php:298) in /home/hosting/web/panel.plomo.gq/public_html/includes/includes.php on line 298

((

**Comment by cdgco** [comment]
I'm sorry, but as I cannot replicate the issue and don't have access to your server, I am unable to diagnose or solve this problem. If you are comfortable with allowing me FTP access or doing further testing, feel free to email me at carter@cdgtech.one. Otherwise, I can only recommend attempting a clean installation, or possibly upgrading to a newer version of PHP.

**Comment by Plata-0-Plomo** [comment]
So shorter:

```
require("../../includes/config.php");` 
require_once( '../../includes/includes.php');
```

**Comment by cdgco** [comment]
The problem is not with a function being declared more than once, just with a script being called more than once, which I do not understand, because includes.php is not called at all in ftp.php and called only once in config.php but they are both giving errors.

**Comment by cdgco** [comment]
The zip file I sent you changed require to require_once, which would have fixed the error if that was the case, but since it didnt, I'm not sure the problem.

**Comment by Efkovole** [comment]
I have same problem :( 

 Fatal error: Cannot redeclare hotKeys() (previously declared in /home/admin/web/mydomain/public_html/includes/includes.php:462) in /home/admin/web/mydomain/public_html/includes/includes.php on line 462
