### ISSUE TITLE
Why this redirection ?

### ISSUE THREAD

**Issue by CLSII** [cdgco/VestaWebInterface#72]
Why redirect to this page and not a local page ?

https://github.com/cdgco/VestaWebInterface/blob/f7d8698e1b2d3753eb9d0a7ececc02a8f535d904/install/install.php#L169

Can you give us the source of this PHP file ?

**Comment by cdgco** [comment]
The page you are redirected to is the page that handles sending welcome emails / adding you to the mailing list about security issues and updates. Because this file contains private API keys it is stored on its own server and not published on GitHub.

In addition to this, the page is also connected to the analytics platform which tracks items such as the location of installations, which features are most commonly enabled, etc, allowing better insight and allowing me to offer custom tailored support to users who do wish to provide their email address.

I plan on switching this to an ajax submission rather than a POST form in the future to remove the refresh.

**Comment by cdgco** [comment]
If you have any further questions or issues about this topic, please reopen this issue.

**Comment by cdgco** [comment]
Redirection removed in commit 0ee5d18.
